export const diversifikasiArticleContent = {
  title: 'Diversifikasi: Kunci Investasi Sukses',
  date: 'Finova Insight Editorial',
  author: 'Tim Finova Insight',
  paragraphs: [
    "Era perekonomian terus berkembang, dengan begitu perusahaan juga harus tetap mengikuti perkembangan permintaan pasar. Tak hanya pelaku bisnis, bagi Anda yang berkecimpung dalam dunia investasi tentu perlu memikirkan strategi yang tepat agar dana Anda bisa berkembang berkali-kali lipat. Salah satu strategi yang sering digunakan untuk menekan risiko kerugian investasi adalah diversifikasi.",
    "Bila diartikan secara sederhana, diversifikasi adalah keberagaman. Namun, jika diterapkan dalam istilah keuangan, diversifikasi berarti sebaran. Sebaran berarti upaya untuk menghindari ketergantungan pada suatu produk, aset, atau dalam hal ini adalah investasi. Para investor biasanya menyebar dana investasinya agar tidak berkumpul di satu aset untuk meminimalisir risiko kerugian.",
    "Pada kesempatan kali ini, kami akan membahas lebih lanjut tentang pentingnya diversifikasi dalam meminimalkan risiko kerugian investasi. Yuk, simak sampai selesai.",
    "Key Takeaways:",
    "- Diversifikasi adalah keberagaman. Dalam investasi, strategi diversifikasi berarti melakukan penyebaran dana investasi ke berbagai instrumen investasi.",
    "- Tujuan dan manfaat utama yang didapatkan dari diversifikasi adalah untuk meminimalisir kerugian yang akan didapat, baik dalam usaha bisnis maupun investasi.",
    "- Secara umum, jenis diversifikasi terbagi menjadi dua, yaitu diversifikasi vertikal dan horizontal.",
    "1. Pengertian Diversifikasi",
    "Dilansir dari Cermati, pengertian diversifikasi menurut Kamus Besar Bahasa Indonesia (KBBI) adalah penganekaragaman. Namun, dalam dunia investasi diversifikasi merupakan strategi dalam menempatkan aset pada sebuah portofolio investasi. Sama seperti diversifikasi bisnis, diversifikasi investasi juga bertujuan untuk meminimalkan risiko dengan cara memadukan beragam jenis instrumen investasi yang tepat untuk portofolio Anda.",
    "Dengan melakukan diversifikasi, berarti Anda sebagai investor telah membeli instrumen investasi yang berbeda-beda untuk mengurangi risiko terjadinya kegagalan investasi apabila performa salah satu instrumen investasi sedang tidak baik. Biasanya strategi diversifikasi ini dilakukan pada investasi reksa dana yang di dalamnya terdapat berbagai macam jenis instrumen investasi, atau investasi saham yang relatif memiliki risiko tinggi.",
    "2. Apa Tujuan dan Manfaat Melakukan Diversifikasi dalam Investasi?",
    "Diversifikasi merupakan salah satu strategi ampuh dalam berinvestasi. Berdasarkan Cermati, berikut ini adalah tujuan diversifikasi beserta manfaat yang akan didapatkan.",
    "a. Meminimalisir Risiko Kerugian",
    "Dengan menggunakan banyak instrumen investasi sebagai tempat untuk meletakkan uang, maka risiko kerugian akan semakin kecil. Karena jika terdapat salah satu instrumen investasi yang bermasalah, Anda masih memiliki pilihan instrumen lain yang bisa membantu meminimalisir risiko tersebut.",
    "b. Membantu Menemukan Strategi Investasi yang Cocok dan Berhasil",
    "Dengan melakukan diversifikasi, Anda sebagai investor bisa terus belajar dan bereksperimen untuk membagi porsi dana investasi ke berbagai instrumen investasi yang tepat sesuai dengan kebutuhan serta kondisi pasar saat itu. Pastinya ketika Anda ingin menemukan strategi investasi yang cocok maka Anda perlu mempertimbangkan profil risiko pribadi, tingkat risiko masing-masing instrumen investasi, serta tujuan dan jangka waktu investasi yang akan dilakukan. Hal ini bisa dilakukan agar Anda bisa menemukan strategi investasi yang cocok dan bisa menawarkan keuntungan yang maksimal dengan risiko kerugian yang minim.",
    "c. Meningkatkan Keuntungan dalam Berinvestasi",
    "Poin ini sebenarnya berkaitan dengan poin sebelumnya, dengan Anda memilih instrumen investasi yang tepat, Anda bisa memaksimalkan keuntungan yang didapat dari berbagai instrumen investasi yang dipilih. Namun, sebelum Anda memilih instrumen investasi, pastikan pilih instrumen yang menawarkan keuntungan paling maksimal sesuai dengan tujuan dan jangka waktu investasi Anda.",
    "d. Mengurangi Ketergantungan pada Satu Jenis Instrumen",
    "Jika Anda berinvestasi pada banyak instrumen, tentu Anda tidak akan memiliki ketergantungan terhadap salah satu instrumen tersebut. Banyaknya instrumen investasi ini meningkatkan keuntungan dan risiko yang berbeda, sehingga jika Anda melakukannya dengan tepat maka Anda bisa menemukan potensi keuntungan di instrumen investasi lain yang bisa mengoptimalkan keuntungan dalam portofolio tanpa harus bergantung pada salah satunya.",
    "e. Menambah Pengetahuan dan Ilmu Investasi",
    "Merujuk pada poin-poin sebelumnya, dengan melakukan diversifikasi berarti Anda akan lebih paham dan berpengalaman dalam mengelola dana investasi pada portofolio. Kemampuan ini nantinya akan membuat Anda bisa membuat keputusan investasi dengan bijak yang membuat portofolio investasi Anda akan mendapatkan keuntungan besar dengan potensi risiko yang bisa ditoleransi.",
    "3. Bentuk dan Jenis Diversifikasi",
    "Terdapat beberapa bentuk dan jenis diversifikasi yang digunakan oleh perusahaan maupun investor. Sebelum membahas lebih dalam, Anda perlu mengetahui tentang dua jenis umum diversifikasi yang biasanya dipakai, yaitu diversifikasi vertikal dan horizontal. Dilansir dari Lifepal, berikut adalah penjelasannya.",
    "- Diversifikasi vertikal, menunjukkan dari atas ke bawah. Sebagai contoh terdapat sebuah perusahaan peternakan sapi, mereka tidak hanya menjual daging sapi melainkan bisa mengembangkan bisnisnya ke produk yang lebih spesifik, seperti produksi kulit sapi yang kemudian menjadi bahan untuk memproduksi sepatu.",
    "- Diversifikasi horizontal, menandakan diversifikasi yang dibuat dengan cara membagi usaha ke samping. Misalnya seperti perusahaan kulit sapi yang akan memproduksi sepatu, tas, dan ikat pinggang. Produk hasil bahan baku kulit sapi itu nantinya disebut sebagai produk diversifikasi horizontal",
    "Selain jenis umum diversifikasi tersebut, terdapat juga tiga jenis penerapan umum strategi diversifikasi yang dilakukan pengusaha atau investor. Berikut penjelasannya di bawah ini.",
    "a. Diversifikasi Portofolio",
    "Jenis diversifikasi ini biasanya dilakukan oleh para investor dengan menginvestasikan dana yang dimiliki ke berbagai produk investasi. Tips untuk melakukan diversifikasi portofolio adalah:",
    "- Paham dengan toleransi risiko, yaitu batasan risiko kerugian yang bisa Anda terima.",
    "- Harus menentukan target aset yang siap diinvestasikan.",
    "- Fokus pada tujuan finansial jangka panjang untuk menghindari sifat labil dan mudah tergiur atas kondisi pasar saat ada potensi keuntungan.",
    "b. Diversifikasi Konglomerat",
    "Ciri khas dari diversifikasi konglomerat ini adalah adanya penambahan produk baru yang dipasarkan untuk target konsumen baru yang tidak berkaitan dengan yang ada saat ini. Supaya berjalan dengan efektif, terdapat beberapa alasan mengapa strategi ini diterapkan:",
    "- Adanya penurunan penjualan yang mengakibatkan penurunan keuntungan.",
    "- Kemampuan manajerial dan modal untuk berkompetisi dalam industri baru.",
    "- Terdapat sinergi dalam sektor keuangan antara dua perusahaan atau lebih dengan alasan pasar jenuh dengan produk yang ada di pasar saat ini.",
    "- Peluang memperoleh bisnis baru yang tidak berkaitan dengan bisnis sebelumnya namun tetap memiliki potensi investasi yang positif.",
    "- Ada ketidakpercayaan atas bisnis yang menjalani saat ini.",
    "Contoh diversifikasi usaha ini adalah perusahaan Johnny Andrean Group yang terkenal dengan usaha salonnya kini merambah ke sektor kuliner, yaitu J.CO Donuts & Coffee. Contoh lainnya adalah PT Wings yang tadinya menjual produk sabun kini merambah ke kuliner dengan produk mi instan, kecap, dan lainnya.",
    "c. Diversifikasi Konsentris",
    "Diversifikasi konsentris berarti penambahan produk baru yang masih ada kaitannya dalam hal teknologi, fasilitas bersama, atau jaringan pemasaran yang sama dengan produk saat ini. Strategi diversifikasi konsentris akan berhasil jika:",
    "- Bersaing dalam industri yang pertumbuhannya tidak signifikan.",
    "- Menaikkan penjualan produk yang sudah ada dengan memproduksi produk baru yang berkaitan dengan produk sebelumnya.",
    "- Menawarkan harga produk baru yang terjangkau dan kompetitif.",
    "d. Diversifikasi Berdasarkan Kelas Aset",
    "Jenis diversifikasi yang satu ini sudah biasa dilakukan oleh manajer investasi maupun investor. Tujuannya adalah untuk menentukan persentase portofolio yang akan dialokasikan ke kelas-kelas aset tersebut. Kelas-kelas aset yang dimaksud adalah seperti saham emiten, obligasi, properti, dana yang diperdagangkan di bursa, komoditas atau barang dasar yang diperlukan untuk produksi produk atau jasa, serta uang tunai dan setara kas.",
    "4. Keuntungan dan Kerugian Diversifikasi",
    "Setelah membaca uraian di atas, tentu Anda sudah tahu bahwa akan banyak keuntungan yang didapatkan jika melakukan diversifikasi. Namun, di samping keuntungan yang didapat, pastinya juga akan ada kerugian yang mengiringi. Dilansir dari Lifepal, berikut adalah peluang keuntungan dan kerugian dari diversifikasi:",
    "a. Keuntungan Diversifikasi",
    "Salah satu keuntungan yang paling banyak dirasakan adalah meminimalisir kerugian yang didapat. Berikut adalah keuntungan lainnya yang bisa Anda dapatkan:",
    "- Meningkatkan pendapatan bagi perusahaan maupun keuntungan dalam investasi.",
    "- Tidak bergantung kepada satu produk untuk mendapatkan keuntungan.",
    "- Untuk bisnis, diversifikasi membuat Anda mampu memenuhi kebutuhan lain dari pelanggan atau konsumen dengan produk yang beragam jenisnya.",
    "- Memperluas pasar dan memberi nilai tambah pada produk.",
    "- Dalam investasi, mampu menambah pengetahuan investor dalam dunia tersebut.",
    "b. Kerugian Diversifikasi",
    "Salah satu kekurangan dari strategi diversifikasi baik bagi pelaku bisnis maupun investor adalah proses yang cukup merepotkan dan melelahkan. Karena Anda akan dihadapi dengan beragam bisnis atau instrumen investasi yang dimiliki, yang berujung pada Anda harus selalu memantau kondisi tersebut. Berikut adalah beberapa kerugian lainnya dari strategi diversifikasi:",
    "- Biaya yang dikeluarkan naik, baik untuk bisnis maupun investasi. Dalam bisnis, jika Anda membuat produk yang berbeda tentunya membutuhkan dana awal yang berbeda pula. Sementara dalam investasi, modal yang diperlukan untuk reksa dana dan properti jelas berbeda jauh.",
    "- Harus melakukan riset karena masuk ke pasar baru dan instrumen baru.",
    "- Perlu perhatian khusus dan orang yang bisa diandalkan untuk mengurus bisnis baru.",
    "- Dalam investasi, terlalu sering melakukan diversifikasi malah bisa menutup peluang bagi investor."
  ]
};
